### ISSUE TITLE
Fable 2.0

### ISSUE THREAD

**Issue by kerams** [ncthbrt/Fable.Websockets.Elmish#2]
Hi, thanks for the library! Any plans to support the new major version of Fable?

**Comment by ncthbrt** [comment]
Hi @kerams, 
Sorry for the delayed reply, I missed this message. 

I'm currently not using Fable as I've been working on some other projects (using Unity) for the last while. Hoping to get back on the F# train in the next few months, but right now I don't currently have any capacity to update this project to support Fable v2.0. 

I've created an organization a while back which holds the offical forks of https://github.com/fable-websockets/Fable.Websockets and https://github.com/fable-websockets/Fable.Websockets.Elmish 

If you'd like to update Websockets Elmish to support the new version, would be happy to give you commit bits.

**Comment by OlegZee** [comment]
Hi @ncthbrt, I did the porting on the local copy in my clone of SAFE-Chat [here](https://github.com/OlegZee/SAFE-Chat/tree/feature/fable-up/src/Client/Websockets) and now porting the changes to clone of Elmish repo.

**Comment by ncthbrt** [comment]
Thanks @OlegZee, your changes look good to me.

**Comment by OlegZee** [comment]
@ncthbrt could you please share ETA for nuget package?

**Comment by ncthbrt** [comment]
Just got back from a holiday. Didn't have reception. I'll be able to publish this tomorrow

**Comment by ncthbrt** [comment]
@OlegZee Also if you'd also like to be a steward of Fable Websockets/Websockets-Elmish, let me know and I can give you the required permissions.

**Comment by OlegZee** [comment]
@ncthbrt good you are back now. I do not mind taking care of this project.

**Comment by ncthbrt** [comment]
As promised. I've published 0.2.0
@OlegZee You'll need a nuget account so that you can publish packages.
